name: Lint

on: push

jobs:
  run-eslint:
    name: Run eslint
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Run lint
        run: yarn lint

  run-code-style:
    name: Run code style check
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Run prettier lint
        run: yarn prettier --check .

  run-code-test:
    name: Run code test check
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Run test
        run: yarn test

  run-code-update-coverage:
    name: Upload coverage reports to Codecov
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        
      - name: Install dependencies
        run: yarn 

      - name: Verify if has tests on project
        run: |
          if [ -z "$(ls -A *.cy.{js,jsx,ts,tsx})" ]; then
            echo "Não há testes no projeto, pulando o fluxo de trabalho"
            exit 0
          fi
        
      - name: Running component tests
        run: yarn cypress run --component
        if: ${{ ne(github.event_name, 'pull_request') && success() && needs.tests.outputs.tests == 'true' }}

      - name: Running e2e tests
        run: yarn cypress run
        if: ${{  ne(github.event_name, 'pull_request') && success() && needs.tests.outputs.tests == 'true' }}

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
