name: Tests

on:
  pull_request:
    branches: 
      - master
      - develop
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/actions@v2
      - run: yarn
      - run: yarn test
        env:
          CI: true
